# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fbd3f56fd89993b7d6019c700fadf9201d7003369591f0c4b86635ab56bfe52f8e9718a9b5487d56e32542b4f4c7d89e918a98763a48c91d53192d31d34a4049

test:
  secret_key_base: f9c467c363d8a1b3717be207e8a5592cdd23f34d264fe7df3593d24fcf13e52363437dd1e9191785125301d382f96f27cb917095c07b911e66de77f1d6ab7b04

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
